### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by focusaurus** [bjrmatos/json-schema-sugar#2]
Hey just a note to say this library looks like what I am looking for so I can share my schema between my application code and my openapi docs. Currently I'm using joi and will try out this module next week. Just wanted to post because it looks like this is a new and undiscovered module but I wanted you to know at least one other person is interested! 💯 🥇

**Comment by bjrmatos** [comment]
Thank you! I really appreciate the time you took to write this. 😄 let me know if in the end it was useful to you.
